// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using smeCore.API.Service.Interface.APIContexts;
using System;

namespace smeCore.API.Migrations
{
    [DbContext(typeof(SMEAPIContext))]
    [Migration("20181220171626_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("smeCore.Models.Authentication.LoggedUser", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiresAt");

                    b.Property<DateTime>("LastLogin");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Username");

                    b.HasKey("id");

                    b.ToTable("LoggedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
